version: '3.8'
services:
  laravelserver:
   build:
    context: ./php
   image: "laravel-image"
   restart: unless-stopped
   ports: 
    - 1234:80 #Laravel
    - 80:8081 #phpMyAdmin
   volumes:
    - ./src:/var/www/html
    - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
    - ./apache/ports.conf:/etc/apache2/sites-enabled/ports.conf
    - ./phpMyAdmin/bash/bash.sh:/var/www/phpMyAdmin/bash/bash.sh
    - ./phpMyAdmin/src/config.inc.php:/var/www/phpMyAdmin/src/config.inc.php

  laraveldb:
   image: mysql
   restart: unless-stopped
   ports: 
    - "4306:3306"
   environment:
    MYSQL_ROOT_PASSWORD: "password"
    MYSQL_DATABASE: "laravel"
    MYSQL_USER: "user"
    MYSQL_PASSWORD: "password"
   volumes:
    - ./dblaravelvol:/var/lib/mysql
  
  


    

